# Server port configuration for AWS Elastic Beanstalk
server.port=5000

spring.application.name=TapTrack

# H2 Database settings for development
spring.datasource.url=jdbc:h2:mem:taptrackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf cache for development
spring.thymeleaf.cache=false
